### ISSUE TITLE
Memory leak in openvino_tensor_representation get_tensor()?

### ISSUE THREAD

**Issue by rychardeh** [luxonis/depthai#185] opened 2020-08-23 16:14 UTC
I've been trying to track down a memory leak which I believe is caused by use of the python API get_tensor() method in the openvino_tensor_representation branch.  If I substitute calling this with returning a similarly sized multidimensional array then I don't see a memory leak so I can only think that this is occurring in the .so library - but I'm not 100% certain.  I've verified with commit [b34f0c95c50b7500886a591f3c6d9fd38750d493](https://github.com/luxonis/depthai/commit/b34f0c95c50b7500886a591f3c6d9fd38750d493).  [Any commits more recent than that fail with a Segmentation fault during device/pipeline initialisation].

**Comment by iamsg-luxonis** [comment] 2020-08-23 17:00
@rychardeh  are you running on RPI or PC? The libs weren't rebuilt for RPI, since it's not yet merged into develop.
Which command line options are you using to run the script ?

**Comment by rychardeh** [comment] 2020-08-23 17:11
RPI.  I rebuilt the API locally (I've found that this is necessary most of the time because the binaries in a given commit don't always match the app code), so whatever API version was matched with that commit.  I'm using my own code, not depthai.py so not sure what you need to know.  My pipeline config is:

config = {
    "streams": [{"name": "previewout"}, {"name": "metaout"}],
    "ai": {
        "blob_file": model_blob,
        "blob_file_config": model_json,
        "shaves": 6,
        "cmx_slices": 6,
        "NN_engines": 2,
        "camera_input": "left_right",
    },
    "camera": {
        "rgb": {
            "resolution_h": 1080,
            "fps": 30,
        },
        "mono": {
            "resolution_h": 400,
            "fps": 12,
        },
    },
}

**Comment by iamsg-luxonis** [comment] 2020-08-23 18:09
@rychardeh  the memory leak issue should be resolved now.
For the record: The problem was the ownership of the numpy array returned.
The RPI lib wasn't rebuilt. This is mainly due to the WIP branch, we rebuild it only before merging. (actually on develop it will be automatically built, at every push). Sorry for the temporary inconvenience. 

If you still have problems, please send me your script, so I can reproduce it.

**Closed** 2020-08-24 10:31 UTC
