### ISSUE TITLE
Watchdog Rewrite to Support Python Interactive Shell

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai#291] opened 2020-12-21 18:19 UTC
### Start with the `why`:

Using the Python interactive shell is quite useful for discovering code-base functionality.  As it stands now, DepthAI cannot support the interactive shell because the watchdog detects the delay from the shell, assumes something has gone wrong, and reboots the DepthAI device.

Supporting the Python Interactive Shell will allow easier discoverability of DepthAI functionality.

### Move to the `how`:

Figure out a way to configure and handle the watchdog so that python interactive shell can be used

https://luxonis.slack.com/archives/CG1PHMY6M/p1602495326208900, see idea https://luxonis.slack.com/archives/CG1PHMY6M/p1602508153217000

### Move to the `what`:

Support the Python Interactive Shell in Gen2 Pipeline Builder (#136).

**Comment by themarpe** [comment] 2020-12-21 20:59
With Gen2 approach, this issue is now resolved. I also did quite a bit of tests with the interactive shell and it worked as intended.
I'll close this for now

**Closed by themarpe** 2020-12-21 20:59 UTC
Labels: Gen2, enhancement
